# sudo: required
language: node_js
node_js:
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
  - '11'

script:
  - npm run lint

notifications:
  email:
    - jeevanjj@live.com

cache:
  directories:
    - node_modules
